name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 여기에 빌드 및 테스트 단계를 추가

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 배포 작업을 여기에 추가

  merge-check:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Check PR approvals
        run: |
          PR_ID=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
          APPROVALS=$(gh pr review-list $PR_ID --json state,user.login --jq 'map(select(.state == "APPROVED")) | length')

          if [ "$APPROVALS" -ge 1 ]; then
            echo "PR has at least one approval."
          else
            echo "PR does not have the required approvals."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
